import Link from "next/link";
import { Logo } from "@/components/logo";

export const metadata = { title: "Terms of Service — Growth Inspector" };

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-white text-slate-950">
      <header className="border-b border-slate-200">
        <div className="mx-auto flex max-w-3xl items-center justify-between px-6 py-5">
          <Link href="/">
            <Logo variant="light" />
          </Link>
          <Link href="/" className="text-sm font-medium text-slate-700 hover:text-slate-950">
            ← Back home
          </Link>
        </div>
      </header>

      <article className="mx-auto max-w-3xl px-6 py-16 text-sm leading-relaxed text-slate-700">
        <h1 className="text-3xl font-bold text-slate-950">Terms of Service</h1>
        <p className="mt-2 text-slate-500">Last updated: July 2026</p>

        <p className="mt-8">
          Growth Inspector is a product operated by <strong>Growth Space</strong>{" "}
          (&ldquo;Growth Space,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or
          &ldquo;our&rdquo;). By creating an account or using Growth Inspector
          (the &ldquo;Service&rdquo;), you agree to these Terms of Service. If
          you do not agree, do not use the Service.
        </p>

        <h2 className="mt-10 text-lg font-semibold text-slate-950">1. The Service</h2>
        <p className="mt-3">
          Growth Inspector connects to your business&rsquo;s social and
          messaging channels and uses AI to read, classify, and draft or send
          replies to customer messages on your behalf, along with analytics
          and reporting about those conversations. You control the reply mode
          (autonomous, approval-required, or off) and the guardrails the AI
          follows for your workspace.
        </p>

        <h2 className="mt-10 text-lg font-semibold text-slate-950">2. Accounts</h2>
        <p className="mt-3">
          You&rsquo;re responsible for the accuracy of the information you
          provide, for keeping your login credentials secure, and for all
          activity that happens under your account or workspace. You must be
          legally authorized to represent the business you connect to the
          Service.
        </p>

        <h2 className="mt-10 text-lg font-semibold text-slate-950">3. AI-generated content</h2>
        <p className="mt-3">
          Replies, summaries, and insights produced by the Service are
          generated by third-party AI models and may occasionally be
          inaccurate, incomplete, or inappropriate for a given context. You are
          responsible for reviewing AI output where you&rsquo;ve enabled
          approval mode, for configuring sensible guardrails, and for how your
          business uses AI-generated replies sent to your customers.
        </p>

        <h2 className="mt-10 text-lg font-semibold text-slate-950">4. Acceptable use</h2>
        <p className="mt-3">You agree not to use the Service to:</p>
        <ul className="mt-3 list-disc space-y-1 pl-5">
          <li>Send spam, unsolicited messages, or content that violates a connected platform&rsquo;s own policies (e.g. WhatsApp, Instagram);</li>
          <li>Send unlawful, deceptive, harassing, or discriminatory content;</li>
          <li>Attempt to disrupt, reverse-engineer, or gain unauthorized access to the Service or other workspaces&rsquo; data;</li>
          <li>Use the Service on behalf of a business you are not authorized to represent.</li>
        </ul>

        <h2 className="mt-10 text-lg font-semibold text-slate-950">5. Plans and billing</h2>
        <p className="mt-3">
          Where a paid plan applies, fees, billing cycle, and any applicable
          taxes will be presented to you before you&rsquo;re charged. We may
          change pricing with advance notice; continued use after a price
          change takes effect constitutes acceptance of the new price.
        </p>

        <h2 className="mt-10 text-lg font-semibold text-slate-950">6. Data</h2>
        <p className="mt-3">
          Our{" "}
          <Link href="/privacy" className="text-emerald-600 underline">
            Privacy Policy
          </Link>{" "}
          describes what data we collect and how we use it, including how
          customer message content is processed by AI providers to generate
          replies and analytics.
        </p>

        <h2 className="mt-10 text-lg font-semibold text-slate-950">7. Termination</h2>
        <p className="mt-3">
          You may stop using the Service and close your workspace at any time.
          We may suspend or terminate access for violation of these Terms, or
          for non-payment on paid plans, with notice where reasonably
          practicable.
        </p>

        <h2 className="mt-10 text-lg font-semibold text-slate-950">8. Disclaimers & liability</h2>
        <p className="mt-3">
          The Service is provided &ldquo;as is&rdquo; without warranties of any
          kind. To the maximum extent permitted by law, Growth Space is not
          liable for indirect, incidental, or consequential damages arising
          from your use of the Service, including from AI-generated replies
          sent on your behalf.
        </p>

        <h2 className="mt-10 text-lg font-semibold text-slate-950">9. Governing law</h2>
        <p className="mt-3">
          These Terms are governed by the laws of the Kingdom of Saudi Arabia,
          without regard to conflict-of-law principles.
        </p>

        <h2 className="mt-10 text-lg font-semibold text-slate-950">10. Contact</h2>
        <p className="mt-3">
          Questions about these Terms? Reach us at{" "}
          <a href="mailto:contact@growth-space.net" className="text-emerald-600 underline">
            contact@growth-space.net
          </a>
          .
        </p>
      </article>
    </main>
  );
}
