import { openrouterChatJSON, OPENROUTER_MODEL_A } from "./openrouter";
import { opencodeChatJSON, OPENCODE_MODEL } from "./opencode";
import { withRetry } from "./retry";
import type { BrandVoice, Intent, Language } from "@/lib/types";

export const HARD_BLOCK_TOPICS = ["politics or government criticism", "religion or religious rulings", "gender / relationship sensitivities", "legal advice", "medical diagnosis or advice", "pricing or refund commitments beyond stated policy"];
export interface MessageAnalysis { intent: Intent; sentiment: "positive" | "neutral" | "negative"; language: Language; lead_score: number; hard_block: boolean; hard_block_reason?: string; }
export interface ResponderResult { analysis: MessageAnalysis; reply: string; confidence: number; decision: "send" | "draft" | "escalate"; escalation_reason?: "low_confidence" | "hard_block_topic" | "high_intent"; }
const COMBINED_RESULT_SCHEMA = { type: "object", properties: { intent: { type: "string", enum: ["price_inquiry", "complaint", "hot_lead", "spam", "support", "other"] }, sentiment: { type: "string", enum: ["positive", "neutral", "negative"] }, language: { type: "string", enum: ["ar", "ar-dialect", "arabizi", "en", "mixed"] }, lead_score: { type: "number" }, hard_block: { type: "boolean" }, hard_block_reason: { type: "string" }, reply: { type: "string" }, confidence: { type: "number" } }, required: ["intent", "sentiment", "language", "lead_score", "hard_block", "hard_block_reason", "reply", "confidence"], additionalProperties: false } as const;
const COMBINED_JSON_SPEC = ["", "Respond with ONLY a JSON object, no prose, with exactly these keys:", '{"intent": "price_inquiry|complaint|hot_lead|spam|support|other",', ' "sentiment": "positive|neutral|negative",', ' "language": "ar|ar-dialect|arabizi|en|mixed",', ' "lead_score": 0-100 integer,', ' "hard_block": true|false,', ' "hard_block_reason": string (empty if none),', ' "reply": string (the customer-facing reply, empty if hard_block or spam),', ' "confidence": 0-1 number}'].join("\n");

function brandVoiceBlock(voice: BrandVoice): string { const parts: string[] = []; if (voice.tone) parts.push(`Tone: ${voice.tone}`); if (voice.facts) parts.push(`Business facts you may use:\n${voice.facts}`); if (voice.guardrails?.length) parts.push(`Never: ${voice.guardrails.join("; ")}`); if (voice.examples?.length) parts.push("Imitate the dialect and style of these past replies:\n" + voice.examples.map((e) => `Customer: ${e.customer}\nReply: ${e.reply}`).join("\n---\n")); return parts.join("\n\n") || "(no brand voice configured yet)"; }
type ResponderOpts = { voice: BrandVoice; replyMode: "autonomous" | "approval" | "off"; threshold: number; history?: { author: string; body: string }[]; channel?: "text" | "voice"; customerName?: string | null };
function decideAction(analysis: MessageAnalysis, confidence: number, replyMode: ResponderOpts["replyMode"], threshold: number): Pick<ResponderResult, "decision" | "escalation_reason"> { if (replyMode === "off") return { decision: "draft" }; if (confidence < threshold) return { decision: "escalate", escalation_reason: "low_confidence" }; if (analysis.intent === "hot_lead" || analysis.lead_score >= 80) return { decision: "escalate", escalation_reason: "high_intent" }; return { decision: replyMode === "autonomous" ? "send" : "draft" }; }
function buildCombinedPrompt(message: string, opts: ResponderOpts) { const history = opts.history ?? []; const convo = history.slice(-6).map((m) => `${m.author}: ${m.body}`).join("\n"); const name = opts.customerName?.trim(); const identityLine = name ? `The customer's name is "${name}". Address them naturally by their first name when it fits. Do NOT use any other name.` : "You do NOT know the customer's name. Never invent, guess, or use a placeholder name — address them politely without one."; const system = ["You are the intelligence layer of Growth Inspector, a Saudi social media AI.", "Understand Saudi Arabic dialects (Khaleeji/Najdi), Arabizi, MSA, English, and code-switching.", "Classify the message AND draft the reply in one pass.", "", "Reply rules:", "- Reply in the EXACT same language and dialect register the customer used.", "- Be warm, concise, and helpful; respect Saudi etiquette and culture.", "- Never invent prices, policies, or commitments not in the brand facts below.", "- If unsure, lower your confidence score rather than guessing.", ...(opts.channel === "voice" ? ["- This reply is SPOKEN on a phone call: 1-3 short natural sentences, no emoji/markdown."] : []), `- ${identityLine}`, "", `Brand voice:\n${brandVoiceBlock(opts.voice)}`, "", "Set hard_block=true for: " + HARD_BLOCK_TOPICS.join("; ") + ". These need a human — leave reply empty.", "If intent is spam, leave reply empty."].join("\n"); return { system: system + COMBINED_JSON_SPEC, user: `${convo ? `Conversation so far:\n${convo}\n\n` : ""}Latest customer message:\n${message}` }; }
function finalizeCombinedResult(parsed: MessageAnalysis & { reply: string; confidence: number }, opts: ResponderOpts): ResponderResult { const analysis: MessageAnalysis = { intent: parsed.intent, sentiment: parsed.sentiment, language: parsed.language, lead_score: parsed.lead_score, hard_block: parsed.hard_block, hard_block_reason: parsed.hard_block_reason }; if (analysis.hard_block) return { analysis, reply: "", confidence: 0, decision: "escalate", escalation_reason: "hard_block_topic" }; if (analysis.intent === "spam") return { analysis, reply: "", confidence: 0, decision: "draft" }; const { decision, escalation_reason } = decideAction(analysis, parsed.confidence, opts.replyMode, opts.threshold); return { analysis, reply: parsed.reply, confidence: parsed.confidence, decision, escalation_reason }; }
export async function respondWithOpenCode(message: string, opts: ResponderOpts): Promise<ResponderResult> { const { system, user } = buildCombinedPrompt(message, opts); const parsed = await withRetry(() => opencodeChatJSON<MessageAnalysis & { reply: string; confidence: number }>({ system, user })); return finalizeCombinedResult(parsed, opts); }
export async function respondWithOpenRouter(message: string, opts: ResponderOpts): Promise<ResponderResult> { const { system, user } = buildCombinedPrompt(message, opts); const parsed = await withRetry(() => openrouterChatJSON<MessageAnalysis & { reply: string; confidence: number }>({ model: OPENROUTER_MODEL_A, system, user })); return finalizeCombinedResult(parsed, opts); }
export class AIUnavailableError extends Error { constructor(message = "Free AI services are temporarily unavailable. Please try again shortly.") { super(message); this.name = "AIUnavailableError"; } }
export async function respondBestAvailable(message: string, opts: ResponderOpts): Promise<ResponderResult> { let lastErr: unknown; try { return await respondWithOpenCode(message, opts); } catch (err) { console.error(`OpenCode (${OPENCODE_MODEL}) failed, falling back to OpenRouter Free Models Router:`, err); lastErr = err; } try { return await respondWithOpenRouter(message, opts); } catch (err) { console.error(`OpenRouter (${OPENROUTER_MODEL_A}) failed:`, err); lastErr = err; } console.error("No free AI provider available:", lastErr); throw new AIUnavailableError(); }
